[env:esp32-s3-zero]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
board_upload.flash_size = 4MB
board_build.partitions = default.csv
build_flags = 
  -DARDUINO_USB_CDC_ON_BOOT=1
  -DBOARD_HAS_PSRAM

lib_deps =
	https://github.com/mrcodetastic/GFX_Lite
  https://github.com/adafruit/Adafruit-GFX-Library.git

monitor_speed = 115200
monitor_filters = esp32_exception_decoder
upload_speed = 921600
check_skip_packages = yes